---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-app
  template:
    metadata:
      labels:
        app: secrets-app
    spec:
      containers:
      - name: secrets-app
        image: docker.io/100691080586/secret-app:v1.0
        imagePullPolicy: Always   
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mysql
          mountPath: "/secrets/mysql"
          readOnly: true     
        - name: paypal
          mountPath: "/secrets/ssl"
          readOnly: true                
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
      volumes:
      - name: mysql
        secret:
          secretName: mysql-credentials
      - name: paypal
        secret:
          secretName: paypal-cert         
  
           