version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "hoanlac9/argocd-example-app"
    revision: "main"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "100691080586/simple-app"
    working_directory: "${{clone}}/source-code"
    tag: main
    tags:
    - "latest"
    - "v1.0"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: dockerhub

  

