---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  annotations:
    code.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        image: ghcr.io/hoanlac9/argocd-example-app:latest
        ports:
        - containerPort: 8080        


